/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.curlp.capapresentacion;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author 50498
 */
public class jFraMDI extends javax.swing.JFrame {

    /**
     * Creates new form jFraMDI
     */
    public jFraMDI() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Imagen de fondo
        JLabel img = new JLabel(" ");
        ImageIcon image = new ImageIcon("C:\\Users\\50498\\Documents\\NetBeansProjects\\INVENTARIOSMASTERPOO\\inventariosmasterpoo\\src\\main\\java\\com\\curlp\\imagenes\\iconfinder_inventory-maintenance_49590.png");
        img.setIcon(image);
        img.setSize(300,220);
        img.setLocation(180, 100);
        img.setVisible(true);
        
        jPanel1.add(img);
    }
    //Abrir Clientes
    private void abrirClientes() throws SQLException{
        JFraCliente cliente = new JFraCliente();
        cliente.setVisible(true);
        
    }
    //Abrir Clientes
    private void abrirEmpleados() throws SQLException{
        jFraEmpleado empleado = new jFraEmpleado();
        empleado.setVisible(true);
        
    }
    //Abrir Clientes
    private void abrirProveedores() throws SQLException{
        jFraProveedor proveedor = new jFraProveedor();
        proveedor.setVisible(true);
        
    }
    //Abrir Clientes
    private void abrirMarcas() throws SQLException{
        jFraMarca marca = new jFraMarca();
        marca.setVisible(true);
        
    }
    //Abrir Clientes
    private void abrirProductos() throws SQLException{
        JFraBuscarProducto producto = new JFraBuscarProducto();
        producto.setVisible(true);
        
    }
    //Abrir Clientes
    private void abrirCategorias() throws SQLException{
        jFraCategoria categoria = new jFraCategoria();
        categoria.setVisible(true);
        
    }
    //Abrir Clientes
    private void abrirFacturas() throws SQLException{
        JFraFactura factura = new JFraFactura();
        factura.setVisible(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtnClientes = new javax.swing.JButton();
        jBtnEmpleados = new javax.swing.JButton();
        jBtnProveedores = new javax.swing.JButton();
        jBtnProductos = new javax.swing.JButton();
        jBtnCategorias = new javax.swing.JButton();
        jBtnFacturas = new javax.swing.JButton();
        jBtnMarcas = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 34, 89));

        jPanel2.setBackground(new java.awt.Color(174, 159, 228));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INVENTARIOS MASTER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jBtnClientes.setBackground(new java.awt.Color(119, 74, 217));
        jBtnClientes.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClientes.setText("Clientes");
        jBtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClientesActionPerformed(evt);
            }
        });

        jBtnEmpleados.setBackground(new java.awt.Color(119, 74, 217));
        jBtnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEmpleados.setText("Empleados");
        jBtnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEmpleadosActionPerformed(evt);
            }
        });

        jBtnProveedores.setBackground(new java.awt.Color(119, 74, 217));
        jBtnProveedores.setForeground(new java.awt.Color(255, 255, 255));
        jBtnProveedores.setText("Proveedores");
        jBtnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProveedoresActionPerformed(evt);
            }
        });

        jBtnProductos.setBackground(new java.awt.Color(119, 74, 217));
        jBtnProductos.setForeground(new java.awt.Color(255, 255, 255));
        jBtnProductos.setText("Productos");
        jBtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProductosActionPerformed(evt);
            }
        });

        jBtnCategorias.setBackground(new java.awt.Color(119, 74, 217));
        jBtnCategorias.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCategorias.setText("Categorías");
        jBtnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCategoriasActionPerformed(evt);
            }
        });

        jBtnFacturas.setBackground(new java.awt.Color(119, 74, 217));
        jBtnFacturas.setForeground(new java.awt.Color(255, 255, 255));
        jBtnFacturas.setText("Facturas");
        jBtnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFacturasActionPerformed(evt);
            }
        });

        jBtnMarcas.setBackground(new java.awt.Color(119, 74, 217));
        jBtnMarcas.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMarcas.setText("Marcas");
        jBtnMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMarcasActionPerformed(evt);
            }
        });

        jBtnSalir.setBackground(new java.awt.Color(119, 74, 217));
        jBtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnMarcas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBtnFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnProductos)
                        .addGap(51, 51, 51)
                        .addComponent(jBtnCategorias)
                        .addGap(47, 47, 47)
                        .addComponent(jBtnFacturas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnClientes)
                        .addGap(51, 51, 51)
                        .addComponent(jBtnEmpleados)
                        .addGap(47, 47, 47)
                        .addComponent(jBtnProveedores)
                        .addGap(49, 49, 49)
                        .addComponent(jBtnMarcas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSalir)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClientesActionPerformed
        try {
            
            abrirClientes();
        } catch (SQLException ex) {
            Logger.getLogger(jFraMDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnClientesActionPerformed

    private void jBtnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEmpleadosActionPerformed
        
          try {
            
            abrirEmpleados();
        } catch (SQLException ex) {
            Logger.getLogger(jFraMDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnEmpleadosActionPerformed

    private void jBtnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProveedoresActionPerformed
        
          try {
            
            abrirProveedores();
        } catch (SQLException ex) {
            Logger.getLogger(jFraMDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnProveedoresActionPerformed

    private void jBtnMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMarcasActionPerformed
        
          try {
            
            abrirMarcas();
        } catch (SQLException ex) {
            Logger.getLogger(jFraMDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnMarcasActionPerformed

    private void jBtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProductosActionPerformed
        
          try {
            
            abrirProductos();
        } catch (SQLException ex) {
            Logger.getLogger(jFraMDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnProductosActionPerformed

    private void jBtnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCategoriasActionPerformed
        
          try {
            
            abrirCategorias();
        } catch (SQLException ex) {
            Logger.getLogger(jFraMDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnCategoriasActionPerformed

    private void jBtnFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFacturasActionPerformed
        
          try {
            
            abrirFacturas();
        } catch (SQLException ex) {
            Logger.getLogger(jFraMDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnFacturasActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFraMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFraMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFraMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFraMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFraMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCategorias;
    private javax.swing.JButton jBtnClientes;
    private javax.swing.JButton jBtnEmpleados;
    private javax.swing.JButton jBtnFacturas;
    private javax.swing.JButton jBtnMarcas;
    private javax.swing.JButton jBtnProductos;
    private javax.swing.JButton jBtnProveedores;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
