/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.curlp.capapresentacion;

import com.curlp.capadatos.CDProducto;
import com.curlp.capalogica.CLProducto;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 50498
 */
public class jFraProducto extends javax.swing.JFrame {

    /**
     * Creates new form jFraProducto
     */
    public jFraProducto() throws SQLException {
        initComponents();
        poblarTabla();
    }
    //Limpiar tabla
    private void limpiarTabla() {
        DefaultTableModel dtm = (DefaultTableModel) this.jTblProducto.getModel();

        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }

    //Poblar tabla
    private void poblarTabla() throws SQLException {
        limpiarTabla();

        CDProducto cdp = new CDProducto();
        List<CLProducto> myList = cdp.obtenerProductos();
        DefaultTableModel temp = (DefaultTableModel) this.jTblProducto.getModel();

        myList.stream().map((CLProducto cl) -> {
            Object[] fila = new Object[6];
            fila[0] = cl.getCodProducto();
            fila[1] = cl.getNombre();
            fila[2] = cl.getDescripcion();
            fila[3] = cl.getCosto();
            fila[4] = cl.getExistencia();
            fila[5] = cl.getPrecioV1();
            fila[6] = cl.getPrecioV2();
            fila[7] = cl.getPrecioV3();
            fila[8] = cl.getNombreCategoria();
            fila[9] = cl.getNombreMarca();
            fila[10] = cl.getNombreEmpresa();
            return fila;
        }).forEachOrdered(temp::addRow);
    }

    //Encontrar Correlativo
    private void encontrarCorrelativo() throws SQLException {
        CDProducto cdp = new CDProducto();
        CLProducto cl = new CLProducto();

        cl.setCodProducto(cdp.autoIncrementarCodProducto());
        this.jTFCodPro.setText(String.valueOf(cl.getCodProducto()));
    }

    //Habilitar y deshabilitar botones
    private void habilitarBotones(boolean guardar, boolean editar, boolean eliminar, boolean limpiar) {
        this.jBtnGuardar.setEnabled(guardar);
        this.jBtnEditar.setEnabled(editar);
        this.jBtnEliminar.setEnabled(eliminar);
        this.jBtnLimpiar.setEnabled(limpiar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFCodPro = new javax.swing.JTextField();
        jTFCosto = new javax.swing.JTextField();
        jBtnGuardar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTFDescripcion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFPrecio2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFExistencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFPrecio1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFPrecio3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFProveedor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFCategoría = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTFNombreMarca9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTFMarca = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblProducto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(174, 159, 228));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Gestión de Productos");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 754, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 1060, 20));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 34, 89));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Cod Producto");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Costo");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jTFCodPro.setEditable(false);
        jPanel4.add(jTFCodPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 109, -1));
        jPanel4.add(jTFCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 109, -1));

        jBtnGuardar.setBackground(new java.awt.Color(119, 74, 217));
        jBtnGuardar.setForeground(java.awt.Color.white);
        jBtnGuardar.setText("Guardar");
        jPanel4.add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jBtnEditar.setBackground(new java.awt.Color(119, 74, 217));
        jBtnEditar.setForeground(java.awt.Color.white);
        jBtnEditar.setText("Editar");
        jBtnEditar.setEnabled(false);
        jPanel4.add(jBtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jBtnEliminar.setBackground(new java.awt.Color(119, 74, 217));
        jBtnEliminar.setForeground(java.awt.Color.white);
        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.setEnabled(false);
        jPanel4.add(jBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        jBtnLimpiar.setBackground(new java.awt.Color(119, 74, 217));
        jBtnLimpiar.setForeground(java.awt.Color.white);
        jBtnLimpiar.setText("Limpiar");
        jPanel4.add(jBtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 237, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Descripcion");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        jPanel4.add(jTFDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 109, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Nombre");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));
        jPanel4.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 109, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Precio 2");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        jPanel4.add(jTFPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 109, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Existencia");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        jPanel4.add(jTFExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 109, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Precio 1");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));
        jPanel4.add(jTFPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 109, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Precio 3");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        jPanel4.add(jTFPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 109, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Proveedor");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));
        jPanel4.add(jTFProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 109, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Categoría");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        jPanel4.add(jTFCategoría, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 109, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Categoría");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        jPanel4.add(jTFNombreMarca9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 109, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Marca");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));
        jPanel4.add(jTFMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 109, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 261, 418));

        jPanel5.setBackground(new java.awt.Color(51, 34, 89));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Producto", "Nombre", "Descripción", "Costo", "Existencia", "Precio 1", "Precio 2", "Precio 3", "Estado", "Categoría", "Id Marca", "Id Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblProducto.setShowGrid(true);
        jScrollPane1.setViewportView(jTblProducto);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 770, 420));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 11, -1, 418));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1060, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel5MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFraProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new jFraProducto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(jFraProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCategoría;
    private javax.swing.JTextField jTFCodPro;
    private javax.swing.JTextField jTFCosto;
    private javax.swing.JTextField jTFDescripcion;
    private javax.swing.JTextField jTFExistencia;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNombreMarca9;
    private javax.swing.JTextField jTFPrecio1;
    private javax.swing.JTextField jTFPrecio2;
    private javax.swing.JTextField jTFPrecio3;
    private javax.swing.JTextField jTFProveedor;
    private javax.swing.JTable jTblProducto;
    // End of variables declaration//GEN-END:variables
}
